### PR TITLE
Refactor code, solve several issues

### PR DESCRIPTION
**Pull request by mtnbarreto**
Fixes #issue(s) .

Changes proposed in this request:
* Selection value now can be any hashable type
* Layout protocol use to arrange subviews in scrollable and non-scrollable navbar items. No longer need to use geometry reader to get the tab size to position the indicator. Simplifies a lot the base code.

### CODE REVIEW

**Comment by mtnbarreto** [comment]
Github action is no loger working... Could you update the tools versions @mats-claassen ?

**Comment by mtnbarreto** [comment]
Readme should be updated. @cecipirotto go ahead if you are willing to do so.

**Comment by coffmark** [comment]
I pulled this branch, but there may already be an error.
I think ProposedViewSize is iOS16 or higher.
So, I think you need available attributes. (like `@available(iOS 16.0, *)`)

I'm looking forward to this changes! Thank you!

**Comment by mtnbarreto** [comment]
Hi @coffmark!

These changes require iOS 16 Layout protocol was just released by apple. I mean it will not longer support ios 15, neither ios 14.

Developers that need iOS 14, and iOS 15 support can continue using older versions, at least until iOS 16 adoption increases.

**Comment by mtnbarreto** [comment]
We already merged these changes,  so i'm closing this pr.

**Pull request closed without merging**
