### PR TITLE
Add: Custom case for fully access to indicator and navigationBar customization

### PR DESCRIPTION
**Pull request by MojtabaHs**
Add infinite possibilities to customize the **Indicator Bar**:

- Circle
- Image
- Animated View
- Async View
- SF Symbol
- Text
- Or any other View the user likes with any customization! 

---
Usage: 
```
.pagerTabStripViewStyle(
    .custom(
        indicator: {
            AnyView(
                Circle()
                    .foregroundColor(.red)
                    .frame(height: 20)
            )
        }
    )
)
```

### CODE REVIEW

**Comment by MojtabaHs** [comment]
Add infinite possibilities to customize the **Navigation Bar** too!

- Color
- Image
- Shadow
- Animated View
- Or any other View the user likes with any customization!

**Comment by MojtabaHs** [comment]
Usage:
```
.pagerTabStripViewStyle(
            .custom(
                tabItemHeight: style.size.buttonHeight,
                background: {
                    AnyView(
                        style.color.formBackground
                            .offset(y: style.size.lineWidth)
                            .shadow(
                                color: style.color.shadow,
                                radius: style.size.shadowRadius,
                                x: 0, y: 5
                            )
                    )
                }
            )
        )
```

**Comment by cecipirotto** [comment]
Hi! thank you for contributing, it looks very nice. Could you please update the Example project and update the readme? so we could release a new version.

**Comment by MojtabaHs** [comment]
Add: Example for the `custom` style to the example project
Add: Documentation to describe the `custom` style inside the README.md file

**Comment by MojtabaHs** [comment]
Add: Better initializer to get rid of the `AnyView` wrapper

**Review by cecipirotto — APPROVED** [review]

**Comment by MojtabaHs** [comment]
Hi! thanks for the merge 🎉!

Is there a reason to squash commits? I personally like to follow the flow of the development of a feature and squashing commits breaks this capability.

**Comment by mats-claassen** [comment]
Yes, we do squash before merging so that in master each feature is found in one commit. So, each PR should include 1 feature which is then merged as 1 commit. Otherwise it's harder to review the history when one feature is implemented in 27 different commits.

**Pull request merged**
